### ISSUE TITLE
无奖征名 _(:з」∠)_

### ISSUE THREAD

**Issue by KenOokamiHoro** [KenOokamiHoro/it_has_not_get_a_name_yet#1]
如题 \_(:з」∠)\_

**Comment by BennyThink** [comment]
萌狼日记。

**Comment by KenOokamiHoro** [comment]
喂那就一点也突不出主题了啊 😂                                 发送方式 Android 版 BlackBerry Hub

**Comment by BennyThink** [comment]
就要这种狼的特色！

**Comment by ShadowRZ** [comment]
V2Ray？
虽然不懂这一块呢

**Comment by ShadowRZ** [comment]
> 萌狼日记。

@BennyThink 这个就放到单独的地方吧

**Comment by outloudvi** [comment]
不如就叫《无名之书》吧？像 deadmau5 的专辑[ > album title goes here < ](https://en.m.wikipedia.org/wiki/Album_Title_Goes_Here) 一样 geek。

**Comment by lmy441900** [comment]
嗯，我想吐嘈一下目前的标题应该是 _It **Has** Not **Got** A Name Yet_ :new_moon_with_face: 
（是该换了）

**Comment by BennyThink** [comment]
@lmy441900 
是的没错，等到差不多完成的时候改下吧:-(

**Comment by KenOokamiHoro** [comment]
@outloudvi "Grimoire of Nameless" ? :joy:

**Comment by KenOokamiHoro** [comment]
或者 "Grimoire of GNU and Tux" ? :joy:

**Comment by rilyuuj** [comment]
抱歉，这个repo干嘛的没有看懂。。

**Comment by ShadowRZ** [comment]
在 2019年1月9日星期三 CST 下午6:12:45，rilyuuj 写道：
> 抱歉，这个repo干嘛的没有看懂。。
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/KenOokamiHoro/it_have_not_get_a_name_yet/issues/1#issueco
> mment-452643042

标题未定的文档集合组。主要是 GNU/Linux 相关
-- 
布偶君 / 心之怪盗团「The Phantom」

**Comment by MarvelousBlack** [comment]
查无此书

**Comment by outloudvi** [comment]
> 抱歉，这个repo干嘛的没有看懂。。

以简体中文编写，面向 GNU/Linux 新用户的指南（大概）

**Comment by ZeroAurora** [comment]
> 查无此书

BookNotFound for GNU/Linux（不是

**Comment by ShadowRZ** [comment]
@ZeroAurora:

>> 查无此书
> 
> BookNotFound for GNU/Linux（不是

这也太皮了🤣🤣🤣🤭🤭🤭

--
Sei

**Comment by KenOokamiHoro** [comment]
@ZeroAurora :joy: 

# 竟然还有人想得起来这个啊，咕咕咕（被打死

**Comment by ZeroAurora** [comment]
@KenOokamiHoro ~~在feed里面看到就进来啦（~~
~~为什么邮件回复不了～～

**Comment by ShadowRZ** [comment]
On Mon, 12 Aug 2019 23:12:06 -0700, @ZeroAurora wrote:

> 为什么邮件回复不了～～

你的邮件客户端需要支援 Reply-To 才能正确用邮件回复

-- 
Sei

**Comment by ZeroAurora** [comment]
试一试哈

用开源、隐私友好的安卓电邮AppFairEmail<https://email.faircode.eu/>发送
