### ISSUE TITLE
重新挖坑（

### ISSUE THREAD

**Issue by KenOokamiHoro** [KenOokamiHoro/it_has_not_get_a_name_yet#23]
如题）
* 基础发行版换成 Arch 了
* 而且可能会放弃虚拟机安装
* emmmm 

https://unmanned.gitbook.io/newworld/

**Comment by BennyThink** [comment]
不跳了，哭哭😭🆒

**Comment by outloudvi** [comment]
摸摸萌狼）
不过用了 Arch Linux / Parabola 的话还能叫“初级” GNU/Linux 魔法书嘛。。

**Comment by KenOokamiHoro** [comment]
@outloudvi emmmm（还是因为自己用习惯了 :joy:

**Comment by BruceZhang1993** [comment]
Arch Linux 挺初级的啊

**Comment by outloudvi** [comment]
@BruceZhang1993  :crying_cat_face:

不过整好最近切换到 Manjaro 上了，写 Arch Linux 相关的东西还是很方便的 :)
