### ISSUE TITLE
建议添加pb使用教程和出现问题该如何查看log并提问？

### ISSUE THREAD

**Issue by MarvelousBlack** [KenOokamiHoro/it_has_not_get_a_name_yet#27]
有很多时候遇到问题都不知道从哪来，或者不知道怎么看 log。于是只能猜，猜对了，好棒。猜错了，emmm，重装好了。而且提问的时候贴 log 不用 pb 一大行，看着很难受呢。

**Comment by KenOokamiHoro** [comment]
https://wiki.archlinux.org/index.php/General_troubleshooting_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87) 不够用了？ :joy:

**Comment by MarvelousBlack** [comment]
emmm，最好寫一下吧，初級指南嘛

**Comment by outloudvi** [comment]
> 当要求贴出 完整 的 输出 / 日志 时，不能仅仅贴出你认为的重要部分。信息来源应该包括：
>
>    所有涉及到的命令的完整输出，不要只选择你认为相关的东西。
>    来自 systemd 的 journalctl 的输出。要获取更多的输出，请使用 systemd.log_level=debug 引导参数。
>    日志文件（看一下 /var/log 目录）
>
>  （后略）

感觉这个对初级用户不能算是「够用」。

**Comment by KenOokamiHoro** [comment]
464a1d136909964bb7c05589bb032f6e188ce7d2 emmm （
